default_language_version:
  python: python3.11

repos:
  # only when working in linux...
-   repo: local
    hooks:
    -   id: export-environment
        name: Export Conda Environment
        entry: bash -c 'mamba env export --no-builds | grep -v "^prefix:" >
          environment.yml && git add environment.yml'
        language: system
        always_run: true
        pass_filenames: false
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-case-conflict
    -   id: check-yaml
        args: ['--unsafe']
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: check-docstring-first
    -   id: file-contents-sorter
    -   id: no-commit-to-branch
        args: ["--branch", "main"]

-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.9.0
    hooks:
    -   id: pre-commit-update

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
    -   id: ruff
        args: ['--fix', '--line-length=120', '--exit-non-zero-on-fix', '--show-fixes']

-   repo: https://github.com/psf/black
    rev: 26.1.0
    hooks:
    -   id: black
        args: ['--line-length=120']

-   repo: https://github.com/pycqa/pylint
    rev: v4.0.4
    hooks:
    -   id: pylint
        args: ['-d duplicate-code', '--disable=W0511, C0103, C0411, line-too-long,
              I1101, import-error, too-few-public-methods, too-many-arguments, too-many-locals,
              too-many-instance-attributes, too-many-branches', '--extension-pkg-allow-list=wandb',
          '--max-positional-arguments=8']

-   repo: https://github.com/asottile/blacken-docs
    rev: 1.20.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==24.2.0]

-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
    -   id: pydocstyle
        additional_dependencies:
        -   tomli

-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config

-   repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
    -   id: isort
        args: ['--profile', 'black', '-o', 'wandb', '-o', 'datasets']

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
    -   id: pyupgrade
        args: ['--py38-plus']
